
spring:
  datasource:
     password: admin
     url : jdbc:mysql://localhost:3306/employeemanager
     username: root
  jpa:
     hibernate:
         ddl-auto: create
     properties:
       hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
     show-sql : true